CREATE TABLE blog_system(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(20) NOT NULL,
	slogan VARCHAR(20) NOT NULL,
	description VARCHAR(255) NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL
) CHARACTER SET utf8 COLLATE utf8_general_ci;