CREATE TABLE blog_categories(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id_blog INT UNSIGNED NOT NULL,
	id_parent INT UNSIGNED NULL,
	name VARCHAR(50) NOT NULL,
	slogan VARCHAR(50) NOT NULL,
	description VARCHAR(255) NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL
) CHARACTER SET utf8 COLLATE utf8_general_ci;